name: CI/CD Pipeline

on:
  push:
    branches:
      - master  # Adjust this to the branch you want to deploy from

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Java and Maven
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Compile and package the application
      - name: Build with Maven
        run: mvn clean compile package -DskipTests

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      # Checkout the repository again in the deploy step
      - name: Checkout code
        uses: actions/checkout@v2

      # SSH into your VM and deploy
      - name: Deploy to VM
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          passphrase: ${{ secrets.VM_SSH_PASSPHRASE }}
          port: 22
          script: |
            # Go to your project directory and replace the JAR
            cd /home/simphiwe/project/infustrature/target/
            rm -f infustraturePortal-0.0.1-SNAPSHOT.jar
            scp -r target/your-springboot-app.jar simphiwe@${{ secrets.VM_HOST }}:/home/simphiwe/project/infustrature/target
            sudo systemctl restart springboot-app.service
